#include "SeguidorDeLinha.h"
#include "Movimentacao.h"


void SeguidorDeLinha::Seguir (int esquerda, int direita){

	if(esquerda > LIMIAR_LINHA && direita > LIMIAR_LINHA){

		set_speed(DEFAULT_LEFT__VOLT_SPEED, DEFAULT_RIGHT_VOLT_SPEED); //SE OS DOIS ESTIVEREM DENTRO DA LINHA, O ROBO ANDARÁ PARA FRENTE

	}else if(esquerda < LIMIAR_LINHA && direita > LIMIAR_LINHA){ // SE O LADO ESQUERDO ESTIVER FORA, O ROBO FARÁ UMA CURVA PARA DIREITA

		setControledRPMSpeed(DEFAULT_LEFT__VOLT_SPEED, DEFAULT_RIGHT_VOLT_SPEED*TURNING_FACTOR);

	}else if (esquerda > LIMIAR_LINHA && direita < LIMIAR_LINHA){ //ANALOGO AO ANTERIOR, 

		setControledRPMSpeed(DEFAULT_LEFT__VOLT_SPEED*TURNING_FACTOR, DEFAULT_RIGHT_VOLT_SPEED);

	}else { //SE OS 2 LADOS ESTIVEREM FORA DA LINHA O ROBO GIRA NO PRÓPRIO EIXO PROCURANDO UMA LINHA

		setControledRPMSpeed(DEFAULT_LEFT__VOLT_SPEED, -DEFAULT_RIGHT_VOLT_SPEED);

	}


}